### ISSUE TITLE
Invite Request - katsumag

### ISSUE THREAD

**Issue by katsumag** [WeLoveOpenSourcePlugins/contribute#2]
I would like to be invited to the *WeLoveOpenSourcePlugins* organisation.

**I plan to contribute:**

Please describe what you will contribute, e.g.:
- ItemActionsLib when it's done 
- any os plugin I make if you want it

**Comment by JohnnyJayJay** [comment]
As of right now, we plan to only include plugins, not libraries, frameworks and the likes, although we may include your library in our list of tools later on.

However as a member, you have the permission to move/copy/create any plugin repository here you want and we will be very happy to see that :)
